### ISSUE TITLE
Support `latest` tag in php-nginx

### ISSUE THREAD

**Issue by apotek** [TugboatQA/images#115]
I discovered the `latest` tag is not being properly set in the services/php-nginx/manifest

```
# Override getTags() to change the NAME to php so we get the correct tags.

function getTagsPhp() {
    NAME=php
    getTags "${FILTER}"
}

FROM=php
FILTER="grep fpm"
GETTAGS=getTagsPhp
```

Zequi Vázquez:
> The manifest is listing all PHP tags whose name includes fpm (see the FILTER variable). This logic would exclude latest as an available tag

Apotek:
> So I could modify that function to filter by fpm and then add back latest?

Zequi Vázquez:
Theoretically, that would work, but I am unsure about it being the best way to achieve it

If there is agreement, I can fix.

**Comment by q0rban** [comment]
I know this is a bit confusing, but I don't believe we want a `latest` tag for this image. That's because we inherit all of our tags from the offical PHP image (and want to continue doing so.) For example, as of this writing, `latest` for the official PHP image is PHP `cli` version 8.2. 

This functions similar to the apache tags for PHP. If you want PHP 8.2 with apache, you must always have the `-apache` suffix on the tag.

I'm going to close this, but feel free to comment with rebuttals and we can reopen if we want to continue the discussion! ☺️

**Comment by apotek** [comment]
Thanks for the explanation James. I didn't realize versions must be specified in tugboat, so `image: tugboatqa/php-nginx` is not supported. Thanks for the reply and yes let's just leave this closed.
