### ISSUE TITLE
Pre-install imagick extension on php images

### ISSUE THREAD

**Issue by apotek** [TugboatQA/images#116]
While users can install imagick extension via .tugboat/config.yml in the `init` step, it seems like a common enough scenario where perhaps it should be baked into the original tugboatqa docker file?

Debian 12 does not allow for installing php-imagick with a simple `apt install php-redis` nor does `docker-php-extension-install redis` work. So it must be installed via PECL on this image, which means it has to be compiled, meaning the `init` phase for tugboat users will be long. 

If there is agreement, I can contribute a patch. Otherwise, please close.

**Comment by q0rban** [comment]
Hi @apotek , I've asked other Lullabots what they think about this!

**Comment by q0rban** [comment]
After some discussion with other Lullabots, everyone is in support of this change, @apotek . Would you like to try your hand at a patch for our php-* Dockerfiles?

**Comment by apotek** [comment]
> After some discussion with other Lullabots, everyone is in support of this change, @apotek . Would you like to try your hand at a patch for our php-* Dockerfiles?

Just started a fork for this work. Thank you @q0rban .

**Comment by YesCT** [comment]
We needed to add 

<img width="975" alt="Screenshot 2023-09-15 at 10 46 37 AM" src="https://github.com/TugboatQA/images/assets/1970586/4322f61d-8100-434a-a6fd-508960664204">


```
        # From: https://command-not-found.com/rsvg-convert
        # rsvg-convert
        # command-line and graphical viewers for SVG files
        apt-get install librsvg2-bin -y --no-install-recommends --quiet
```

to our tugboat config so that we could resolve an error showing in the recent log messages when uploading an svg.

Error was like: 
`Message	ImageMagick error 1: identify-im6.q16: delegate failed `'rsvg-convert' -o '%o' '%i'' @ error/delegate.c/InvokeDelegate/1958. identify-im6.q16: unable to open file `/tmp/magick-260Z-6w41hrcK4O': No such file or directory @ error/constitute.c/ReadImage/600. [command: identify -format 'format:%[magick]|width:%[width]|height:%[height]|colorspace:%[colorspace]|profiles:%[profiles]|exif_orientation:%[EXIF:Orientation]\n' '/var/lib/tugboat/web/sites/default/files/Blank_US_Map_(states_only).svg']`

Could there be something missing from the tugboat image?

**Comment by apotek** [comment]
> Could there be something missing from the tugboat image?

Hi @YesCT! Imagick only installs SVG support in its extras package, so a default installation doesn't include it. This is by design. As I understand it, the maintainers don't include it due to the security concerns in processing SVG files. SVG files can be a vector for malware if the source of them is not controlled.
